sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: l6H15XUTQ5ba5frb0Tby22hWamRXK+TilvOqP7rWC9iiSvQdzw6zN7ZvKUh6hgszQnMnd4h1u+5ZA6WfLXs/4jc0k31VFph4ix7dZaFd7WQ+6PYhRUFfaRRLe5nQ4cva3T4YKnKUvuVHhjHv3KaVUO1IMbTC8DjBC0UfvveQMl73fDzDCbSeTfrZtiKkf+3dwFKlKx1KmZ0jhJuevNrGLjBzidkVv+C/lCQ8jq77kEcsmLpU5XYsw2BkAZw7qJO7To7PRLeGIe4iGX9SomViJa+FxLrBeqbw+L4VZpFGH22FKq05MnAGOM+T3bnj2aRaAaz6rNzxwKcoDK00s82HoqOTrDoi1KtM+p8xZBUe0S2u29PWSeu02joLrCMjYuFHnwWhurOC0f8BaYOYyO36fsXoUndaSAHGaxYaSfKCXS430qJSX78YpiQI5r3nYBfMC4mM0KiUWB4829tDMD3OHVqAivpGmsYHA9AoP+nZFuXrY76HdPTrZbMdaDMay34RbOOJCiRhYdAEtcOa7qsQQX+vdYD8U5sPVV8dBIMQForeGM8kiAq7QnXBFfjSSXatz0/joJC2eMsBGNBJHt8+TCgbWbBiQU9fjZMlXwqqVyk1YPdTfctDRGsiEgD3WLOobt76MVsPGW+XY056zCXFggyC++fxpbaME5dB7w7CZZs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/When-the-World-Shook--13-Being-an-Account-of-the-Great-Adventure-of-Bastin-Bickley-and-Arbuthn__1368
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy